services:
  c1: 
    build:
      context: ./c1
      dockerfile: Dockerfile
    networks:
      - ssh_network

  c2:
    build:
      context: ./c2
      dockerfile: Dockerfile
    networks:
      - ssh_network
  c3:
    build:
      context: ./c3
      dockerfile: Dockerfile
    networks:
      - ssh_network
  c4:
    build:
      context: ./c4
      dockerfile: Dockerfile
    platform: linux/amd64
    networks:
      - ssh_network
  s1:
    build:
      context: ./s1
      dockerfile: Dockerfile
    networks:
      - ssh_network

networks:
  ssh_network:
    driver: bridge